spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url:
    driver-class-name:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

    properties:
      format-sql: true
      hibernate:
        show-sql: true
        format_sql: true

  mail:
    username:
    password:
    host:
    port:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:

